// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGS0zSUe5MwW0pmcLhT2Optd1cJMAzXCQ',
    appId: '1:109029831525:web:3fecedb48ef52dae70a78c',
    messagingSenderId: '109029831525',
    projectId: 'basededonnee-49abc',
    authDomain: 'basededonnee-49abc.firebaseapp.com',
    storageBucket: 'basededonnee-49abc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuPfigBRuxmFFAHMuDHcn2_-OdWDWVB8',
    appId: '1:109029831525:android:9d8883bc69f217fe70a78c',
    messagingSenderId: '109029831525',
    projectId: 'basededonnee-49abc',
    storageBucket: 'basededonnee-49abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuLWj0p9SQZ3ImCijR2xNC1BA5t_7yE2w',
    appId: '1:109029831525:ios:4d0f00350b42bfd870a78c',
    messagingSenderId: '109029831525',
    projectId: 'basededonnee-49abc',
    storageBucket: 'basededonnee-49abc.appspot.com',
    iosClientId: '109029831525-e6k8b63rl77ngsa8nd5m09rgls929r3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.followUp11',
  );
}
